version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install awscli aws-sam-cli

  build:
    commands:
      - sam build --debug --use-container

  post_build:
    commands:
      - sam package --template .aws-sam/build/template.yaml --output-template-file packaged-template.yaml --s3-bucket bannerdecompressionlambda-artifacts

artifacts:
  files:
    - packaged-template.yaml