#!/bin/bash

#This script should be run inside a lambci/lambda:build-python3.7 docker image
#with the current directory mounted to /mnt inside the container
#e.g. using - `docker run -v $(pwd):/mnt lambci/lambda:build-python3.7 /mnt/run_unit_tests`


export PYTHONPATH=/mnt/.aws-sam/build/CommonFunctionsLayer/python:$PYTHONPATH

cd /mnt/.aws-sam/build/DecompressBz2Function && \
python -m unittest discover && \
cd /mnt/.aws-sam/build/DecompressGZFunction && \
python -m unittest discover && \
cd /mnt/.aws-sam/build/DecompressSnappyFunction && \
python -m unittest discover && \
cd /mnt/.aws-sam/build/DecompressZlibFunction && \
python -m unittest discover && \
cd /mnt/.aws-sam/build/DecompressZstdFunction && \
python -m unittest discover